### ISSUE TITLE
How to check available printers?

### ISSUE THREAD

**Issue by ansgmlen** [3screens/cordova-brother-label-printer#1]
I am trying to integrate with this model
Brother High-Speed Label Printer with Wireless Networking (QL710W)

in Cordova project.
Is it possible to work this printer?
Thanks

**Comment by gordol** [comment]
Hi @ansgmlen, sorry for the late response, I just noticed your message here...

See here for a list of compatible printers: http://www.brother.com/product/dev/mobile/android/index.htm

QL-710W is indeed compatible.

I just updated the project README with some instructions on how to configure your printer for use with this plugin.

Just put your model name here: https://github.com/3screens/cordova-brother-label-printer/blob/master/src/android/BrotherPrinter.java#L50
