### ISSUE TITLE
printViaSDK gives error

### ISSUE THREAD

**Issue by chetuBhadra93** [3screens/cordova-brother-label-printer#22]
Hello,
I am getting following error after calling printViaSDK.

Error: "The passed in data did not seem to be a decodable image. 
Please ensure it is a base64 encoded string of a supported Android format"

I am passing base64 string. So please give any sample base64 string or give some feedback.

Thanks.

**Comment by VictorCoding** [comment]
are you including `data:image/png;base64`, if so you shouldn't. just include everything else after that.

**Comment by gordol** [comment]
Correct, you should only send the image data. It does not specify to use a data URL, but base64 encoded image.

> printViaSDK takes one parameter, which is a base64 encoded bitmap image. The result should be a status code that is passed directly from the SDK. The status codes are documnted in the Brother SDK Appendix in section 4.2.2.5.Error Code. If everything works, the response should be "ERROR_NONE".

**Comment by chetuBhadra93** [comment]
Hello,
Thanks for your response.
I tried that too. But when i pass base64 string without data:image/png;base64, the app is crashed. 
So can you provide me a sample code for it.

When I try to debug in BrotherPrinter.java file, I note one thing I got base64 image but my application is crashed when **"mBitmapPrint.print();"** is called.

Thanks in advance.

**Comment by gordol** [comment]
@chetuBhadra93 can you share your code?

What platform are you on?

Have you tried the master branch?

I cannot vouch for the validity of the dev branch, as it is un-tested.

**Comment by chetuBhadra93** [comment]
Hello,
Thanks for response.
I am using android platform and dev branch.

**Comment by gordol** [comment]
Does the master branch work for you? @chetuBhadra93

**Comment by chetuBhadra93** [comment]
Yes, I tried master branch. I got printer in findPrinter but when i call printViaSDK it does not give any error but it also not printing anything. And when i try to debug I log this info.
**"Model: QL_720NW Port: NET PrintMode: ORIGINAL Orientation: PORTRAIT PaperSize: CUSTOM ipAddress: 192.168.x.xx macAddress: 54:xx:xx:xx:xx:xx"**

My model number is: QL-810.

what should i pass for my model in this code
**"myPrinterInfo.printerModel  = PrinterInfo.Model."**

Can you please help me to figure out this issue..?

**Comment by chetuBhadra93** [comment]
I successfully print label for Model QL-810 using Master branch for android platform.

**Comment by firdaus48** [comment]
Hello,
I am getting following error after calling printViaSDK.

Error: "Unexpected Internal System Error: IllegalArgumentException"

using printer brother QL-1110NWB

Thank you. please help

**Comment by VictorCoding** [comment]
@firdaus48 can you show us your code?

**Comment by firdaus48** [comment]
@VictorCoding this issue has been solved, with update the latest SDK that supported QL-1110NWB model.

Thank u

**Comment by yogeshshsf** [comment]
Hi, i am getting error while calling printViaSDK. The error is '**The passed in data did not seem to be a decodable image. Please ensure it is a base64 encoded string of a supported Android format**'.  
I have excluded `data:image/png;base64`  as mentioned by @VictorCoding. can someone help me on this please, thanks in advance.


  
```
cordova.plugins.brotherPrinter.findNetworkPrinters((data)=>{
        var printerResponse = data[0];
        var printer = {
          "model": printerResponse.model,
          "port": printerResponse.port,
          "modelName": printerResponse.modelName,
          "ipAddress": printerResponse.ipAddress,
          "macAddress": printerResponse.macAddress,
          "nodeName": printerResponse.nodeName,
          "location": ""
        }

        cordova.plugins.brotherPrinter.setPrinter(printer, function (success) {
          var imageString = base64Image.split(',')[1];
          var dataArray = {
            "base64String": imageString,
            "numberOfCopies": 1
          };
          cordova.plugins.brotherPrinter.printViaSDK([dataArray], (data) => {
            console.log('print success');
          }, (error)=> {
            console.log('error:', error);
          })
        });
      },(err)=>{
          console.log("Error");
          console.log(err)
});`

**Comment by VictorCoding** [comment]
> Hi, i am getting error while calling printViaSDK. The error is '**The passed in data did not seem to be a decodable image. Please ensure it is a base64 encoded string of a supported Android format**'.
> I have excluded `data:image/png;base64` as mentioned by @VictorCoding. can someone help me on this please, thanks in advance.
> 
> ```
> cordova.plugins.brotherPrinter.findNetworkPrinters((data)=>{
>         var printerResponse = data[0];
>         var printer = {
>           "model": printerResponse.model,
>           "port": printerResponse.port,
>           "modelName": printerResponse.modelName,
>           "ipAddress": printerResponse.ipAddress,
>           "macAddress": printerResponse.macAddress,
>           "nodeName": printerResponse.nodeName,
>           "location": ""
>         }
> 
>         cordova.plugins.brotherPrinter.setPrinter(printer, function (success) {
>           var imageString = base64Image.split(',')[1];
>           var dataArray = {
>             "base64String": imageString,
>             "numberOfCopies": 1
>           };
>           cordova.plugins.brotherPrinter.printViaSDK([dataArray], (data) => {
>             console.log('print success');
>           }, (error)=> {
>             console.log('error:', error);
>           })
>         });
>       },(err)=>{
>           console.log("Error");
>           console.log(err)
> });`
>    
> ```

Maybe the base64 is corrupted? I would validate that it's actually valid just for a sanity check. Stick it in an image tag to verify.

**Comment by yogeshshsf** [comment]
@VictorCoding it is a valid image i am display while printing the badge `              <img src="{{base64Image}}" width="200" height="200">
`

**Comment by VictorCoding** [comment]
@yogeshshsf welp, no idea then 🤷‍♂

**Comment by gordol** [comment]
Try a bitmap instead of png?

**Comment by yogeshshsf** [comment]
@gordol how to convert base64string to bitmap?
