### ISSUE TITLE
printViaSDK callback does not run when encountering WLAN error

### ISSUE THREAD

**Issue by VictorCoding** [3screens/cordova-brother-label-printer#23]
I've purposely been triggering a network error to occur when calling printViaSDK by having my ipad connected to a different network than that of the brother printer, however the callback never gets runned, instead I see this in my safari and xcode consoles `error: Error occured while WLAN printing`. Which is line `557` in `BrotherPrinter.m` file.

https://github.com/gordol/cordova-brother-label-printer/blob/dev/src/ios/BrotherPrinter.m#L557

It would be great if the callback actually got triggered with a good error as a response that way I can handle that on the js side. Otherwise, the js side has no idea why the printer didn't print since the callback never gets invoked.
Any help would be appreciated.

**Comment by gordol** [comment]
What is outputted by this line:

`NSLog(@"Communication Result: %d", result);`

If there is a result, then line 557 would never be executed.

I didn't write this IOS code, so I can't be of much help...

You're running off the Dev branch, which I'm not really supporting yet.

If you have issues, please follow up here: https://github.com/gordol/cordova-brother-label-printer/pull/11

So the author can help resolve, and we can keep IOS efforts organized in one place.

**Comment by VictorCoding** [comment]
@gordol Just fyi, what I'm saying is that there is NO result, which is why line 557 IS getting run. And that's where it ends, I dont get my callback invoked.

Thanks, i'll go ahead and take it to that other issue.
