### ISSUE TITLE
Is dev branch working for iOS platform

### ISSUE THREAD

**Issue by chetuBhadra93** [3screens/cordova-brother-label-printer#24]
Hello, I have QL-810W. And I want to print from iOS. So dev branch plugin working for QL-810W...?

**Comment by chetuBhadra93** [comment]
Hello @gordol ,
Can you please let me know dev branch is working for QL-810W wireless printer..?
I will help me to focus and work on it for my iOS application.

**Comment by gordol** [comment]
I don't know, the changes on the dev branch were done by others here: https://github.com/gordol/cordova-brother-label-printer/pull/10

Please use https://github.com/gordol/cordova-brother-label-printer/pull/11 for further discussion about IOS efforts.
