### ISSUE TITLE
Upgrade the Bundled SDK

### ISSUE THREAD

**Issue by NgYueHong** [3screens/cordova-brother-label-printer#26]
This is the awesome plugin I have been searching for. It would be great if the bundled SDK can be upgraded to the latest version to keep it relevant and useful for everyone, especially those with newer model of printer.

**Comment by gordol** [comment]
Do you know if the latest SDK is compatible?

Pull requests are welcomed.

**Comment by gordol** [comment]
@NgYueHong please try this and let me know if it works: 

https://github.com/gordol/cordova-brother-label-printer/tree/brother-sdk-upgrade
