### ISSUE TITLE
Broken in Cordova 8

### ISSUE THREAD

**Issue by cpgb85** [3screens/cordova-brother-label-printer#27]
Looks like this plugin is broken in cordova 8.  I get the error that /platforms/android/AndroidManifest.xml does not exist. It looks like Cordova changed the folder structure.

**Comment by gordol** [comment]
Hmm...

The platform manifest file should be created at run-time, right?

See here: https://github.com/gordol/cordova-brother-label-printer/blob/master/plugin.xml#L39
```xml
        <config-file target="AndroidManifest.xml" parent="/manifest">
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
            <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.USB" />
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
            <uses-feature android:name="android.hardware.usb" android:required="true" />
        </config-file>
```

According to the release notes, this actually changed in Version 7 of Cordova, not 8.
https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html


```xml
<!-- An existing config.xml -->
<edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">

<!-- needs to change to -->
<edit-config file="app/src/main/AndroidManifest.xml" target="/manifest/application" mode="merge">
```

Can you give that a try? If it works, I'm happy to accept a pull request.

**Comment by gordol** [comment]
We may need to overhaul permissions to request at run-time too...

**Comment by stanislavdavid** [comment]
is is broken in cordova 8 which includes cordova-android 7 :-)
