### ISSUE TITLE
NPE When Printing

### ISSUE THREAD

**Issue by eugenedw** [3screens/cordova-brother-label-printer#28]
I've built and rebuilt but continue to receive nullpointerexceptions in logs when trying to print:

java.lang.NullPointerException: Attempt to get length of null array
    at com.brother.ptouch.sdk.Printer.tempFileDelete(Printer.java:766)
    at com.brother.ptouch.sdk.Printer.finish(Printer.java:1756)
    at com.brother.ptouch.sdk.Printer.getLabelInfo(Printer.java:1570)
    at com.brother.ptouch.sdk.Printer.checkLabelInPrinter(Printer.java:1615)
    at com.threescreens.cordova.plugin.brotherPrinter.BrotherPrinter$2.run(BrotherPrinter.java:209)

Debugging the application shows that this occurs when attempting to delete temp files. 

Any ideas?

**Comment by gordol** [comment]
What branch and revision are you on?

Are you using the latest brother SDK or the older one?

Looks to me like that NPE is coming from within the SDK... but maybe something changed in recent versions and we need to update the BrotherPrinter.java module.

**Comment by eugenedw** [comment]
Thanks for writing back. And also, thank you for putting in the work to create this plugin. Great job!

I spent several hours digging into this since my post. I went as far as downloading, building and debugging the sample app that comes with the latest Brother SDK. After researching, it turns out that there were two key issues:

1. There needs to be an explicit permissions request before printing can be performed due to the fact that the libraries attempt to write a temporary file to the filesystem. I'm using ionic 3 and followed instructions outlined here: https://ionicframework.com/docs/native/android-permissions/

2. The second issue related to the label size. I had to update your BrotherPrinter.java code's "printViaSdk" method so as to remove deprecated methods and to include the proper label size for this QL720NW that I'm using. Thanks to the sample app, trial and error led to the right size. Here's an excerpt. If you'd like, I can create a pull request

                    myPrinterInfo.labelNameIndex = LabelInfo.QL700.valueOf("W62H100").ordinal();
                    myPrinterInfo.isAutoCut = true;
                    myPrinterInfo.isCutAtEnd = true;

I can think of a few other things that can be added to this plugin to enhance it, such as adding the ability to print a pdf, providing a printer selection capability, and providing a means of specifying paper size.

Again, thanks for your work on this!

**Comment by eugenedw** [comment]
In the latest update to the fork I'd created prior to the pull request, I've added the ability to print a pdf with the plugin. Really needed that function.

**Comment by gordol** [comment]
Isn't the PDF functionality exempt from the public SDK? I believe it was previously, anyway... and it required a non-distributable library. The one included with the SDK watermarked the PDFs, and was limited in other ways too, I believe.

I'm happy to support it, but we need to be careful in how we implement it, if these restrictions still exist.

**Comment by gordol** [comment]
I have a QL720NW here too, but I haven't worked with this plugin in well over a year or so. Previously the SDK supported a method to read the current label in the printer, and it was not necessary to hard-code it. Was there a regression there on Brother's part in the newer SDK? Or is there a problem in the current implementation of reading the label from the printer itself? It should not need to be hard coded...

**Comment by gordol** [comment]
My point is, I have the contact info for some people at Brother, and if there's a legitimate regression here, and the deprecated method is the one that reads the label from the printer... well... I'm going to give someone an ear-full. ;)

**Comment by gordol** [comment]
We could always build up a monstrosity of hard-coded configurations for each printer in a huge switch statement or something, but that really is horrible, and shouldn't be necessary. :(
