### ISSUE TITLE
[INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by B-PRAVEEN** [3screens/cordova-brother-label-printer#33]
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.1
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Environment Variables:

    ANDROID_HOME : /Users/praveen/Library/Android/sdk

Error on running - ionic cordova run android

after adding this plugin it start showing the error.

> CordovaError: Error executing "adb -s emulator-5554 install -r "/Users/praveen/Documents/Project/VMS-PRINT/brother/platforms/android/build/outputs/apk/debug/android-debug.apk"": adb: failed to install /Users/praveen/Documents/Project/VMS-PRINT/brother/platforms/android/build/outputs/apk/debug/android-debug.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by gordol** [comment]
The brother SDK has native libraries that are pre-compiled, and does not support the architecture you're attempting to test with.

Read more about ABIs here: https://developer.android.com/ndk/guides/abis

The Android SDK that is currently bundled only supports ARM CPUs, but your android emulator is likely using x86.

You can update to the latest brother SDK from here: http://www.brother.co.jp/eng/dev/mobilesdk/download/index.aspx#android

But they may have broken the API/compatibility, so we may need a few code changes here to support the latest SDK. However, the latest SDK does have x86/x86_64 support.
