### ISSUE TITLE
"CGBitmapContextCreate: unsupported parameter combination" when trying to print

### ISSUE THREAD

**Issue by rhohn94** [3screens/cordova-brother-label-printer#39]
The code that I am using is based on Ayiga's pull request, pull request #15 .

The error, however, comes from BRPtouchPrinter.print, and seems to be caused by bad parameters being passed to a call to CGBitmapContextCreate. Here's the exact error message that I get:

![38171742_1876559235981706_8463269181737926656_n](https://user-images.githubusercontent.com/40176545/43543993-43071444-9597-11e8-8def-a69e5217c83b.png)

Has anyone else encountered this? The image that I'm sending is ultimately derived from a base64 encoded (image/jpeg) that I get from an HTML canvas.  I haven't changed any of the code that handles the base64 image data received from the Cordova side of the application.

I am printing via bluetooth., and I am testing this on an early-generation iPad Mini. The printer is a QL-820NWB. Aside from changing the default value for the label size, I have not adjusted any kind of configuration for the printer in the code.

**Comment by gordol** [comment]
the brother sdk requires a bitmap, not jpeg. if their native sdk can convert other formats, great, but i'm not sure...
