### ISSUE TITLE
Ionic - undefined is not an object 

### ISSUE THREAD

**Issue by kieranbarlow** [3screens/cordova-brother-label-printer#40]
I'm trying to use this plugin with a new Ionic app, when pulling in the plugin and calling the plugin in my home controller as a test, hooking up a button to fire one of the functions on this plugin. Code & error message below.

I'm testing this via the Ionic Serve command with the Ionic DevApp.

**Part of my home component**
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Printer, PrintOptions } from '@ionic-native/printer';

declare var cordova; // DECLARING Cordova

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
   constructor(public navCtrl: NavController, private printer: Printer) {...}
...
```

**Test Function**
```
brotherTest() {
    cordova.plugins.brotherPrinter.findNetworkPrinters((data)=>{
        console.log("Success");
        console.log(data)
    },(err)=>{
        console.log("Error");
        console.log(err)
    });
  }
```

**Error Message**

> undefined is not an object (evaluating 'cordova.plugins.brotherPrinter.findNetworkPrinters')

**Comment by gordol** [comment]
dunno what to tell you... what specifically is undefined? you didn't say...

make sure the plugin is actually installed, regenerate platform if need be. what platform btw?

sorry I can't be more help, you didn't give much to go on. shouldn't you use $ionicPlatform.ready and $window.cordova?

**Comment by gordol** [comment]
https://ionicframework.com/docs/v1/angularjs/utils/platform/

**Comment by gordol** [comment]
Hello, did you ever figure this out? Feel free to re-open if you still have issues.
