### ISSUE TITLE
Crush in android 8 oreo

### ISSUE THREAD

**Issue by LucaStorto** [3screens/cordova-brother-label-printer#41]
Hello
I wanted to report that in Android 8 hours or the plugin does not work .. tested with honor 9 lite and huawei mediapad m5
whether the printsdk method or the printwifi is used

**Comment by gordol** [comment]
Can you provide more details? What Cordova version are you using, which Brother SDK version, and which version of this plugin?

**Comment by gordol** [comment]
Also a stack trace would be helpful....

**Comment by LucaStorto** [comment]
hi I've been using
8.1.2 (cordova-lib@8.1.1)
Ionic 4.2.1
brother sdk 3013
plugin version 0.0.3

also using the dev repository plugin and in bluetooth you have the same problem using the platform android@7.1.1
