### ISSUE TITLE
 ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by aadevsol** [3screens/cordova-brother-label-printer#44]
On android 7.0.0 after I install the plugin I receive the following error: 

(node:17824) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'path\platforms\android\res\xml\config.xml'

can somebody help me with this? I really need to make this work, please

**Comment by aadevsol** [comment]
If I downgrade to android 6, it works ... but when I try cordova.plugins.brotherPrinter.findPrinters , I receive the following message : cordova.plugins.brotherPrinter.findPrinters is not a function 

there is no functions on cordova.plugins.brotherPrinter

any solve for this?

**Comment by aadevsol** [comment]
I succeeded to make it work using this plugin https://github.com/MmtBkn/cordova-brother-label-printer 

but now I have another problem:  cordova.plugins.brotherPrinter.findPrinters returns an empty array ... what should I do to make it work?

**Comment by gordol** [comment]
i don't provide support for forks, sorry... ask the author of the fork.

**Comment by aadevsol** [comment]
Ok, then you know why I have the first bug? because the first one is not a fork

**Comment by gordol** [comment]
I can't really help you without seeing your project.

Are you using Cordova, or Ionic?

What versions of Cordova/Ionic?

What version of Android studio are you using?

You have not provided enough details to assist with your issue.

Simply downgrading your cordova android version is not sufficient, you must completely remove and re-install your plugins. This is a standard cordova workflow, it has nothing to do with this plugin.

If your project doesn't find the cordova plugin methods then you have not properly installed the plugin.

**Comment by aadevsol** [comment]
I am using ionic 3 , version "3.9.2" 
I installed the plugin using cmd in solution folder, and this command : "cordova plugin add git+https://github.com/gordol/cordova-brother-label-printer.git"

I think that I use the latest version of android studio

**Comment by gordol** [comment]
Have you tried searching the internet with your error message? I find tons and tons of messages from frustrated Ionic and Cordova users... I don't think these errors have anything to do with this plugin.

https://www.google.com/search?q=UnhandledPromiseRejectionWarning%3A+Error%3A+ENOENT%3A+no+such+file+or+directory%2C+open+%27path%5Cplatforms%5Candroid%5Cres%5Cxml%5Cconfig.xml%27

**Comment by aadevsol** [comment]
Yeah, I searched and found a lot of messages like that one but none worked ... I think that you are right and it is a Ionic problem ... Omg I am so done with hybrid apps

**Comment by gordol** [comment]
Most of these issues are probably caused by the move from eclipse style projects to android studio style projects. Ionic is a buggy mess, and I haven't developed using it in many years. Sorry, I can't be of more assistance. Hybrid apps are a pain in the ass... but so are native.

**Comment by gordol** [comment]
I would try to follow the Ionic setup guide from scratch, and maybe it'll work.

**Comment by aadevsol** [comment]
Thank you for your time, I will try again and come back with an answer to help others... thanks

**Comment by gordol** [comment]
This may be relevant: https://gist.github.com/joeljeske/68121fa6d643e0937f50458d0172e16e

**Comment by gordol** [comment]
For sure! Sorry you're having so much trouble...

**Comment by gordol** [comment]
https://ionic.zone/cordova/update

**Comment by gordol** [comment]
Maybe your tooling is just out of date.

**Comment by aadevsol** [comment]
this might be a problem, will definitely  try to update this, thank you man

**Comment by gordol** [comment]
No problem... Good luck.
