### ISSUE TITLE
Problem to add the plugin on angularJS Code

### ISSUE THREAD

**Issue by Hiugsor** [3screens/cordova-brother-label-printer#5]
Hi,

First, I would thank the creator of the plugin for his work.

I'm trying to add the plugin on an Ionic Angular code, but despite the documentation, i don't know how to call the plugin's functions. If it work like other cordova plugins, we shoud call them like:

`cordova.plugins.BrotherPrinter.findNetworkPrinters();
cordova.plugins.BrotherPrinter.printViaSDK(doc);`

or

`window.plugin.BrotherPrinter.findNetworkPrinters(); 
 window.plugin.BrotherPrinter.printViaSDK(doc);`

i added the plugin on my cordova plugin list, and I presume that I have nothing else to do but call the functions.

i'm doing something wrong and i would know if there are subtleties to know for the implementation of the code which is not in the usage doc.

And, i don't understand why the print input must be a bitmap and not a string (it's just curiosity).

NB : a small working exemple would be great.

Thank a lot for your answers.

**Comment by Hiugsor** [comment]
This plugin is officially dead and there is no longer any contributor to give an easy answer??

Can you explain more how you use your functions. printViaSDK is not able to reconize the call of findNetworkPrinter. Unless it is necessary to give it an input variable that is not quoted in the doc ...

**Comment by gordol** [comment]
There is nothing special about this...

It's just 3 methods and they forward calls to the native java code: https://github.com/3screens/cordova-brother-label-printer/blob/master/www/printer.js

Examples:
```js
cordova.plugins.brotherPrinter.findNetworkPrinters(function (found, printerList) {
    //do stuff with printer search results here
});

cordova.plugins.brotherPrinter.printViaSDK(data, function (response) {
    ///do stuff with print response here
});
```

**Comment by RSF-Deus** [comment]
It is admirable to have taken the time to answer to my friend now, but we do now have our own solution as you may be aware so nothing to be worry about :) he is a begginer in Cordova Plugins technology and that's where I came to help.
Still, I would like to take some time to say FUCK YOU BROTHER for not providing a JavaScript / Web SDK, me and my friend lost almost an entire month of work because of that, it is utterly unprofessionnal. And of course they do not answer to e-mails...

**Comment by gordol** [comment]
I have had pretty good luck contacting Brother, but we contacted them via our company, not as an individual, and we also purchased a lot of printers from them for a client... soooo... yeah that probably helps to get a rep on the phone.

They provide an example app for IOS, but it's HORRIBLE. Instead I elected to reverse engineer the core pieces while reviewing their horrific documentation... This is most definitely not a full implementation, just the pieces we needed for basic functionality.

**Comment by RSF-Deus** [comment]
Interesting to know about the iOS part, guess I'll tell my team to maybe not consider porting our app to iOS if possible, actually we are also part of a company that purchased a lot of printers from them ! Maybe we didn't say the magic word ? :D

**Comment by gordol** [comment]
I meant to say Android, not iOS. :) Sorry...

**Comment by gordol** [comment]
But judging by what I saw in their Android app, the iOS one is probably just as bad. Haha!
