### ISSUE TITLE
Thanks to your plugin, I was able to make my own.

### ISSUE THREAD

**Issue by RSF-Deus** [3screens/cordova-brother-label-printer#6]
Tell me what you think about it ! If you ever happen to still work on it : 

https://github.com/Random-Shit-Factory/BrotherPrinterCordova

**Comment by gordol** [comment]
Hi, it really would have been nice if you had forked normally so you could push your changes back to help make this plugin better. 

Instead, you lifted all the code into your own repo, and removed our attribution and copyright notice from the license and replaced it with your own.

Now your repository can't be merged back with ours easily.


Glad this was of some help at least, and please do feel free to send pull requests.

**Comment by RSF-Deus** [comment]
oops, I'm kind of a begginner with cordova plugins etc... So I started "from scratch" with a plugin example code from another user who provides a blank cordova plugin interface, but I didn't take your code and adapt it, I inspired myself from it, if you look at the code you'll notice that it has almost no ressemblance to yours, it is actually even not using the same libraries. You were just my starting point that motivated me doing this, I just wanted to thank you personnally. But it wasn't a modified clone from your repository, sorry for the confusion ! If I want to be able to send a pull request I'll have to clone from your repo and then inject my code that is right ?

**Comment by gordol** [comment]
Ahh, I didn't really look closely so I didn't realize you just use the same structure and rewrote everything. Neat...

Best of luck with it!
